package com.nju.test.entity;

import java.io.Serializable;

public class Address implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.user_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.user_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.user_tel
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address_id
     *
     * @return the value of t_address.address_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address_id
     *
     * @param addressId the value for t_address.address_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.user_id
     *
     * @return the value of t_address.user_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.user_id
     *
     * @param userId the value for t_address.user_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.user_name
     *
     * @return the value of t_address.user_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.user_name
     *
     * @param userName the value for t_address.user_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address
     *
     * @return the value of t_address.address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address
     *
     * @param address the value for t_address.address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.user_tel
     *
     * @return the value of t_address.user_tel
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.user_tel
     *
     * @param userTel the value for t_address.user_tel
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel;
    }

    @Override
    public String toString() {
        return "Address{" +
                "addressId=" + addressId +
                ", userId=" + userId +
                ", userName='" + userName + '\'' +
                ", address='" + address + '\'' +
                ", userTel='" + userTel + '\'' +
                '}';
    }
}