package com.nju.test.entity;

import java.io.Serializable;
import java.util.List;

public class Category implements Serializable {

    private List<Goods> goodslist;

    public List<Goods> getGoodslist() {
        return goodslist;
    }

    public void setGoodslist(List<Goods> goodslist) {
        this.goodslist = goodslist;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.t_store_store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer tStoreStoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_id
     *
     * @return the value of t_category.category_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_id
     *
     * @param categoryId the value for t_category.category_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_name
     *
     * @return the value of t_category.category_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_name
     *
     * @param categoryName the value for t_category.category_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.t_store_store_id
     *
     * @return the value of t_category.t_store_store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer gettStoreStoreId() {
        return tStoreStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.t_store_store_id
     *
     * @param tStoreStoreId the value for t_category.t_store_store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void settStoreStoreId(Integer tStoreStoreId) {
        this.tStoreStoreId = tStoreStoreId;
    }
}