package com.nju.test.entity;

import java.io.Serializable;

public class OrderGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.order_goods_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer orderGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.goods_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.goods_count
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.goods_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.goods_image
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String goodsImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.order_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_goods
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.order_goods_id
     *
     * @return the value of t_order_goods.order_goods_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getOrderGoodsId() {
        return orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.order_goods_id
     *
     * @param orderGoodsId the value for t_order_goods.order_goods_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setOrderGoodsId(Integer orderGoodsId) {
        this.orderGoodsId = orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.goods_name
     *
     * @return the value of t_order_goods.goods_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.goods_name
     *
     * @param goodsName the value for t_order_goods.goods_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.goods_count
     *
     * @return the value of t_order_goods.goods_count
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.goods_count
     *
     * @param goodsCount the value for t_order_goods.goods_count
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.goods_price
     *
     * @return the value of t_order_goods.goods_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.goods_price
     *
     * @param goodsPrice the value for t_order_goods.goods_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.goods_image
     *
     * @return the value of t_order_goods.goods_image
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getGoodsImage() {
        return goodsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.goods_image
     *
     * @param goodsImage the value for t_order_goods.goods_image
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setGoodsImage(String goodsImage) {
        this.goodsImage = goodsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.order_id
     *
     * @return the value of t_order_goods.order_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.order_id
     *
     * @param orderId the value for t_order_goods.order_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
}