package com.nju.test.entity;

import java.io.Serializable;
import java.util.List;

public class Order implements Serializable {

    private List<OrderGoods> goods;

    public List<OrderGoods> getGoods() {
        return goods;
    }

    public void setGoods(List<OrderGoods> goods) {
        this.goods = goods;
    }

    private Integer commentFlag;

    public Integer getCommentFlag() {
        return commentFlag;
    }

    public void setCommentFlag(Integer commentFlag) {
        this.commentFlag = commentFlag;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.arrive_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String arriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.delivery_side
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String deliverySide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_way
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.delivery_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Float deliveryCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.preferential_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Float preferentialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Float payCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_id
     *
     * @return the value of t_order.store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_id
     *
     * @param storeId the value for t_order.store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_name
     *
     * @return the value of t_order.store_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_name
     *
     * @param storeName the value for t_order.store_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_time
     *
     * @return the value of t_order.order_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_time
     *
     * @param orderTime the value for t_order.order_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.arrive_time
     *
     * @return the value of t_order.arrive_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.arrive_time
     *
     * @param arriveTime the value for t_order.arrive_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setArriveTime(String arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.address
     *
     * @return the value of t_order.address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.address
     *
     * @param address the value for t_order.address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.delivery_side
     *
     * @return the value of t_order.delivery_side
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getDeliverySide() {
        return deliverySide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.delivery_side
     *
     * @param deliverySide the value for t_order.delivery_side
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setDeliverySide(String deliverySide) {
        this.deliverySide = deliverySide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_way
     *
     * @return the value of t_order.pay_way
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_way
     *
     * @param payWay the value for t_order.pay_way
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.delivery_cost
     *
     * @return the value of t_order.delivery_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Float getDeliveryCost() {
        return deliveryCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.delivery_cost
     *
     * @param deliveryCost the value for t_order.delivery_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setDeliveryCost(Float deliveryCost) {
        this.deliveryCost = deliveryCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.preferential_price
     *
     * @return the value of t_order.preferential_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Float getPreferentialPrice() {
        return preferentialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.preferential_price
     *
     * @param preferentialPrice the value for t_order.preferential_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setPreferentialPrice(Float preferentialPrice) {
        this.preferentialPrice = preferentialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_cost
     *
     * @return the value of t_order.pay_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Float getPayCost() {
        return payCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_cost
     *
     * @param payCost the value for t_order.pay_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setPayCost(Float payCost) {
        this.payCost = payCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}