package com.nju.test.entity;

import java.io.Serializable;

public class Store implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.sales_amount
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer salesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_grade
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Float storeGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.sending_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer sendingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.delivery_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Float deliveryCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_distance
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private Integer storeDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_activity_tip1
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeActivityTip1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_activity_tip2
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeActivityTip2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_image
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.brief_introduction
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String briefIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_notice
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_tel
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.send_start_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String sendStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.sent_end_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String sentEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.store_qualification
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private String storeQualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_store
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_id
     *
     * @return the value of t_store.store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_id
     *
     * @param storeId the value for t_store.store_id
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_name
     *
     * @return the value of t_store.store_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_name
     *
     * @param storeName the value for t_store.store_name
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.sales_amount
     *
     * @return the value of t_store.sales_amount
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getSalesAmount() {
        return salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.sales_amount
     *
     * @param salesAmount the value for t_store.sales_amount
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setSalesAmount(Integer salesAmount) {
        this.salesAmount = salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_grade
     *
     * @return the value of t_store.store_grade
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Float getStoreGrade() {
        return storeGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_grade
     *
     * @param storeGrade the value for t_store.store_grade
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreGrade(Float storeGrade) {
        this.storeGrade = storeGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.sending_price
     *
     * @return the value of t_store.sending_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getSendingPrice() {
        return sendingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.sending_price
     *
     * @param sendingPrice the value for t_store.sending_price
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setSendingPrice(Integer sendingPrice) {
        this.sendingPrice = sendingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.delivery_cost
     *
     * @return the value of t_store.delivery_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Float getDeliveryCost() {
        return deliveryCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.delivery_cost
     *
     * @param deliveryCost the value for t_store.delivery_cost
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setDeliveryCost(Float deliveryCost) {
        this.deliveryCost = deliveryCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_distance
     *
     * @return the value of t_store.store_distance
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public Integer getStoreDistance() {
        return storeDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_distance
     *
     * @param storeDistance the value for t_store.store_distance
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreDistance(Integer storeDistance) {
        this.storeDistance = storeDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_activity_tip1
     *
     * @return the value of t_store.store_activity_tip1
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreActivityTip1() {
        return storeActivityTip1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_activity_tip1
     *
     * @param storeActivityTip1 the value for t_store.store_activity_tip1
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreActivityTip1(String storeActivityTip1) {
        this.storeActivityTip1 = storeActivityTip1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_activity_tip2
     *
     * @return the value of t_store.store_activity_tip2
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreActivityTip2() {
        return storeActivityTip2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_activity_tip2
     *
     * @param storeActivityTip2 the value for t_store.store_activity_tip2
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreActivityTip2(String storeActivityTip2) {
        this.storeActivityTip2 = storeActivityTip2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_image
     *
     * @return the value of t_store.store_image
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreImage() {
        return storeImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_image
     *
     * @param storeImage the value for t_store.store_image
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreImage(String storeImage) {
        this.storeImage = storeImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.brief_introduction
     *
     * @return the value of t_store.brief_introduction
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getBriefIntroduction() {
        return briefIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.brief_introduction
     *
     * @param briefIntroduction the value for t_store.brief_introduction
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setBriefIntroduction(String briefIntroduction) {
        this.briefIntroduction = briefIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_notice
     *
     * @return the value of t_store.store_notice
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreNotice() {
        return storeNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_notice
     *
     * @param storeNotice the value for t_store.store_notice
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreNotice(String storeNotice) {
        this.storeNotice = storeNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_tel
     *
     * @return the value of t_store.store_tel
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreTel() {
        return storeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_tel
     *
     * @param storeTel the value for t_store.store_tel
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreTel(String storeTel) {
        this.storeTel = storeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_address
     *
     * @return the value of t_store.store_address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreAddress() {
        return storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_address
     *
     * @param storeAddress the value for t_store.store_address
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.send_start_time
     *
     * @return the value of t_store.send_start_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getSendStartTime() {
        return sendStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.send_start_time
     *
     * @param sendStartTime the value for t_store.send_start_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setSendStartTime(String sendStartTime) {
        this.sendStartTime = sendStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.sent_end_time
     *
     * @return the value of t_store.sent_end_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getSentEndTime() {
        return sentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.sent_end_time
     *
     * @param sentEndTime the value for t_store.sent_end_time
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setSentEndTime(String sentEndTime) {
        this.sentEndTime = sentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.store_qualification
     *
     * @return the value of t_store.store_qualification
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public String getStoreQualification() {
        return storeQualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.store_qualification
     *
     * @param storeQualification the value for t_store.store_qualification
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    public void setStoreQualification(String storeQualification) {
        this.storeQualification = storeQualification;
    }
}