package com.nju.test.dao;

import com.nju.test.entity.OrderGoods;
import java.util.List;

public interface OrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    int deleteByPrimaryKey(Integer orderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    int insert(OrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    OrderGoods selectByPrimaryKey(Integer orderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    List<OrderGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbggenerated Tue Apr 03 08:57:43 CST 2018
     */
    int updateByPrimaryKey(OrderGoods record);
}